language: python

python:
  - 3.6

services:
  - docker

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov

install:
  - pip install .

script: 
  # - docker-compose build 
  # - docker-compose up -d
  - docker-compose -f tests/fortitester/docker-compose.yml up -d
  # - docker-compose ps
  - docker-compose -f tests/fortitester/docker-compose.yml ps
  # - pytest tests/fortitester/test_fortitester.py -v -s --cov-report term --cov-report html:htmlcov --cov=nefila
  - pytest tests/fortitester/test_fortitester.py --verbose --capture=no

# notifications:


# after_success:
#   - codecov
